name: Check
on: push
jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Dependencies
        run: |
          corepack enable
          yarn set version stable
          yarn install
      - name: Lint
        run: yarn lint --config .prettierrc.json
