name: Check
on: push
jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'yarn'
      - name: Setup .yarnrc.yml
        run: yarn config set npmScopes.buf.npmRegistryServer "https://buf.build/gen/npm/v1"
      - name: Dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
