name: Check
on: push
jobs:
  Check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Node
        uses: actions/setup-node@v4
        with:
          node-version: 22.5.1
      - name: Setup yarn
        run: corepack enable
      - name: Dependencies
        run: yarn install
      - name: Lint
        run: yarn lint
      - name: Test
        run: npx ng test --code-coverage --source-map=false --browsers=ChromeHeadless --watch=false
      - name: Build
        run: yarn build
